<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\AnimalShelter.BLL\AnimalShelter.BLL.csproj" />
    <ProjectReference Include="..\AnimalShelter.DAL\AnimalShelter.DAL.csproj" />
    <ProjectReference Include="..\AnimalShelter.Core\AnimalShelter.Core.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="dotenv.net" Version="4.0.2" />
  </ItemGroup>

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
